FORMAT: 1A
HOST: http://api.mango.dev

# mango

modular architecture powered by RethinkDb and GoLang

# Data Structures

## Test (object)
+ id: testid (string, required)
+ title: eleven (string, required)
+ description: cute creature from upside up (string, required)
+ created_at: `2016-10-10T08:40:51.620Z` (required)
+ updated_at: `2016-10-10T08:40:51.620Z` (required)

## User (object)
+ id: userid (string, required)
+ name: james vincent (string, required)
+ email: koko@koko.com (string, required)
+ created_at: `2016-10-10T08:40:51.620Z` (required)
+ updated_at: `2016-10-10T08:40:51.620Z` (required)


# Group Test
Get or set tags on notes

## Test [/test]

### List [GET]
+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Test])

### Create [POST]
+ Request (application/json; charset=utf-8)
    + Attributes (Test)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)

## Test Detail [/test/{id}]
### Detail [GET]
+ Parameters
    + id: `testid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)

### Update [PATCH]
+ Parameters
    + id: `testid` (string, required)
+ Request (application/json; charset=utf-8)
    + Attributes (Test)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)

### Remove [DELETE]
+ Parameters
    + id: `testid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)


# Group User
Group description (also with *Markdown*)

## User [/user]

### List [GET]
+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[User])

### Create [POST]
+ Request (application/json; charset=utf-8)
    + Attributes (User)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (User)

## User Detail [/user/{id}]
### Detail [GET]
+ Parameters
    + id: `userid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (User)

### Update [PATCH]
+ Parameters
    + id: `userid` (string, required)
+ Request (application/json; charset=utf-8)
    + Attributes (User)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (User)

### Remove [DELETE]
+ Parameters
    + id: `userid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (User)
