FORMAT: 1A
HOST: http://api.mango.dev

# mango

modular architecture powered by RethinkDb and GoLang

# Data Structures

## Test (object)
+ id: testid (string, required)
+ title: eleven (string, required)
+ description: cute creature from upside up (string, required)
+ created_at: `2014-11-11T08:40:51.620Z` (required)
+ updated_at: `2014-11-11T08:40:51.620Z` (required)

## Test [/test]

### List [GET]
+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Test, Test, Test])

### Create [POST]
+ Request (application/json; charset=utf-8)
    + Attributes (Test)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)

## Test Detail [/test/{id}]
### Detail [GET]
+ Parameters
    + id: `testid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)

### Update [PATCH]
+ Parameters
    + id: `testid` (string, required)
+ Request (application/json; charset=utf-8)
    + Attributes (Test)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)

### Remove [DELETE]
+ Parameters
    + id: `testid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)
