FORMAT: 1A
HOST: http://api.mango.dev

# mango

modular architecture powered by RethinkDb and GoLang

# Data Structures

## Test (object)
+ id: testid (string, required)
+ title: eleven (string, required)
+ description: cute creature from upside up (string, required)
+ created_at: `2016-10-10T08:40:51.620Z`
+ updated_at: `2016-10-10T08:40:51.620Z`

## User (object)
+ id: userid (string, required)
+ type: admin (string, required)
+ name: james vincent (string, required)
+ email: koko@mango.com (string, required)
+ password: somehashpassword (string, required)
+ created_at: `2016-10-10T08:40:51.620Z`
+ updated_at: `2016-10-10T08:40:51.620Z`

## File (object)
+ id: fileid (string, required)
+ slug: somefilehash (string, required)
+ mime: image/png (string, required)
+ size: 12 (number, required)
+ created_at: `2016-10-10T08:40:51.620Z`
+ updated_at: `2016-10-10T08:40:51.620Z`

# Group Auth
Authentication instructions

## Register [/register]
### Register [POST]
+ Request (application/json; charset=utf-8)
    + Attributes
        + name: james vincent (string, required)
        + type: admin (string, required)
        + email: testlogin@mango.com (string, required)
        + password: admin (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (User)

## Login [/login]
### Login [POST]
+ Request (application/json; charset=utf-8)
    + Attributes
        + email: testlogin@mango.com (string, required)
        + password: admin (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + id: testid (string, required)
        + type: admin (string, required)
        + token: somejwttoken (string, required)

## Me [/me]
+ Model
    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3Rsb2dpbmlkIiwidHlwZSI6ImFkbWluIn0.lK3wXjmLPjt9TgB6n-TxRmTGC5RII1P5OeHfRehzW2k
### Me [GET]
+ Request (application/json; charset=utf-8)
    [Me][]
+ Response 200 (application/json; charset=utf-8)
    + Attributes (User)



# Group Test
Test endpoint for quick start

## Test [/test]
### Create [POST]
+ Request (application/json; charset=utf-8)
    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3Rsb2dpbmlkIiwidHlwZSI6ImFkbWluIn0.lK3wXjmLPjt9TgB6n-TxRmTGC5RII1P5OeHfRehzW2k
    + Attributes (Test)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)
### List [GET]
+ Request (application/json; charset=utf-8)
    [Me][]
+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[Test])

## Test Detail [/test/{id}]
### Detail [GET]
+ Request (application/json; charset=utf-8)
    [Me][]
+ Parameters
    + id: `testid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)
### Update [PATCH]
+ Parameters
    + id: `testid` (string, required)
+ Request (application/json; charset=utf-8)
    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3Rsb2dpbmlkIiwidHlwZSI6ImFkbWluIn0.lK3wXjmLPjt9TgB6n-TxRmTGC5RII1P5OeHfRehzW2k
    + Attributes (Test)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)
### Remove [DELETE]
+ Request (application/json; charset=utf-8)
    [Me][]
+ Parameters
    + id: `testid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (Test)



# Group User
User endpoint for quick start

## User [/user]
### Create [POST]
+ Request (application/json; charset=utf-8)
    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3Rsb2dpbmlkIiwidHlwZSI6ImFkbWluIn0.lK3wXjmLPjt9TgB6n-TxRmTGC5RII1P5OeHfRehzW2k
    + Attributes (User)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (User)
### List [GET]
+ Request (application/json; charset=utf-8)
    [Me][]
+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[User])

## User Detail [/user/{id}]
### Detail [GET]
+ Request (application/json; charset=utf-8)
    [Me][]
+ Parameters
    + id: `userid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (User)
### Update [PATCH]
+ Parameters
    + id: `userid` (string, required)
+ Request (application/json; charset=utf-8)
    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3Rsb2dpbmlkIiwidHlwZSI6ImFkbWluIn0.lK3wXjmLPjt9TgB6n-TxRmTGC5RII1P5OeHfRehzW2k
    + Attributes (User)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (User)
### Remove [DELETE]
+ Request (application/json; charset=utf-8)
    [Me][]
+ Parameters
    + id: `userid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (User)



# Group File
File endpoint for quick start

## File [/file]
### Create [POST]
+ Request (application/json; charset=utf-8)
    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3Rsb2dpbmlkIiwidHlwZSI6ImFkbWluIn0.lK3wXjmLPjt9TgB6n-TxRmTGC5RII1P5OeHfRehzW2k
    + Attributes (File)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (File)
### List [GET]
+ Request (application/json; charset=utf-8)
    [Me][]
+ Response 200 (application/json; charset=utf-8)
    + Attributes (array[File])

## File Detail [/file/{id}]
### Detail [GET]
+ Request (application/json; charset=utf-8)
    [Me][]
+ Parameters
    + id: `fileid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (File)
### Update [PATCH]
+ Parameters
    + id: `fileid` (string, required)
+ Request (application/json; charset=utf-8)
    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3Rsb2dpbmlkIiwidHlwZSI6ImFkbWluIn0.lK3wXjmLPjt9TgB6n-TxRmTGC5RII1P5OeHfRehzW2k
    + Attributes (File)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (File)
### Remove [DELETE]
+ Request (application/json; charset=utf-8)
    [Me][]
+ Parameters
    + id: `fileid` (string, required)
+ Response 200 (application/json; charset=utf-8)
    + Attributes (File)
